### ISSUE TITLE
Board boots only after press reset button

### ISSUE THREAD

**Issue by subzero2379** [skiselev/micro_8088#14]
If i cold boot no post ,if i press reset board boots,how board manages reset on cold boot is capacitor 10uf?

**Comment by skiselev** [comment]
The C20 capacitor is indeed 10 uF. I don't have the same issue, and it is the first time I hear about such a problem.
It is possible that your power supply ramps up voltages too slowly.
Is this issue reproduceable with a different power supply?

**Comment by subzero2379** [comment]
Ok resolved recapped my psu teo capacitors leaking
And boots fine

**Comment by skiselev** [comment]
Good to hear!
