### ISSUE TITLE
Cannot locate FE2010

### ISSUE THREAD

**Issue by cbmeeks** [skiselev/micro_8088#2]
I really want to build this board.  But I cannot find a Faraday FE2010A (or similar) chip.  Maybe my eBay searching skills are failing me.  Do you happen to know of a place where I could buy one?

Thanks_

**Comment by skiselev** [comment]
Here is one on [eBay](https://www.ebay.com/itm/1pcs-FE2010A-JU-FE2010-PLCC84-FARADAY/263277266243)
Also check Chinese distributors, e.g. [UtSource](https://www.utsource.net/)

**Comment by cbmeeks** [comment]
I don't know how I missed that.

Thank you!

**Comment by skiselev** [comment]
You're welcome! I am closing this issue.
