### ISSUE TITLE
Broken link for AT2XT PIC12F629 firmware

### ISSUE THREAD

**Issue by wrljet** [skiselev/micro_8088#20]
In the building instructions:

**7. Program the PIC12F629 microcontroller with the** [AT2XT Firmware](https://github.com/skiselev/micro_8088/blob/master/www.vcfed.org/forum/showthread.php?26426-AT2XT-keyboard-converter)

The link doesn't work anymore.

Perhaps [this is the correct link?](https://forum.vcfed.org/index.php?threads/at2xt-keyboard-converter.26861/post-1242916)

Bill

**Comment by skiselev** [comment]
Bill, thank you for reporting it!
Fixed here: https://github.com/skiselev/micro_8088/commit/74707ecbe01a6988f483716e44d132f57d15f9d2
