### ISSUE TITLE
Missing Kicad Libraries

### ISSUE THREAD

**Issue by kwadwobro1** [skiselev/micro_8088#3]
Kicad complain with the error 

The following libraries were not found:

74ls-sergey.lib

dallas-rtc.lib

devices-sergey.lib

intel-8xxx.lib

memory-sergey.lib

transistors.lib

conn.lib

linear.lib

regul.lib

cmos4000.lib

adc-dac.lib

memory.lib

xilinx.lib

special.lib

microcontrollers.lib

dsp.lib

microchip.lib

analog_switches.lib

motorola.lib

texas.lib

intel.lib

digital-audio.lib

philips.lib

display.lib

cypress.lib

siliconi.lib

opto.lib

atmel.lib

contrib.lib

valves.lib

when you open the project file in Kicad

**Comment by skiselev** [comment]
I think you can safely delete these libraries. These were default libraries from an older KiCad version. All the custom components should be [my_kicad_library](https://github.com/skiselev/my_kicad_library) repository.
Please let me know if the schematic editor doesn't properly show components (run an ERC too).
