### ISSUE TITLE
Updated link for AT2XT Firmware

### ISSUE THREAD

**Issue by prabathbr** [skiselev/micro_8088#7]
The given links in the README.md for "AT2XT Firmware" is dead due to forum upgrade.
New link for the post containing "XTATKEY_094.zip" is : 

https://forum.vcfed.org/index.php?threads/at-to-xt-keyboard-converter.16050/post-304769

**Comment by skiselev** [comment]
Thank you for reporting this broken link!
I've updated the README.

**Comment by prabathbr** [comment]
Hi, I also found below link where it is available to download without registering in a forum. 
I haven't personally used this though.

https://hackaday.io/project/166433-at2xt-keyboard-adapter
